use std::path::PathBuf;

use kiroshi_app::commands::builder;
use kiroshi_app::missions::contract::{MissionDraft, MissionEntry, MissionNote};
use kiroshi_app::routines::contract::{RunRequested, TriggerEvent};
use specta_typescript::Typescript;

const HEADER: &str = "// Generated by tauri-specta from the Rust command surface. Do not edit.\n// Run `cargo test --manifest-path apps/app/src-tauri/Cargo.toml --features fake-claude` to regenerate.\n";

#[test]
fn bindings_mirror_the_command_surface() {
	builder()
		.typ::<MissionDraft>()
		.typ::<MissionEntry>()
		.typ::<MissionNote>()
		.typ::<RunRequested>()
		.typ::<TriggerEvent>()
		.dangerously_cast_bigints_to_number()
		.export(
			Typescript::default().header(HEADER),
			PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/lib/bindings.ts"),
		)
		.expect("bindings export");
}
