import type { SpaceGraphData } from "@workspace/ui/components/space-graph-model"

const ALL_BOTS = ["bot-atlas", "bot-basile", "bot-clemence", "bot-dorian"]

const SPACE_GRAPH: SpaceGraphData = {
	space: { id: "space-orbit", name: "Orbit" },
	observedAt: "2026-03-04T09:30:00Z",
	bots: [
		{ id: "bot-atlas", name: "Atlas", blot: "blue", isWorking: true },
		{ id: "bot-basile", name: "Basile", blot: "purple", isWorking: false },
		{ id: "bot-clemence", name: "Clémence", blot: "pink", isWorking: true },
		{ id: "bot-dorian", name: "Dorian", blot: "orange", isWorking: false },
	],
	plugins: [
		{
			id: "system-prompt",
			name: "system-prompt.md",
			kind: "file",
			scope: "system",
			tokens: 6200,
			lastWriteAt: "2026-01-12T08:00:00Z",
			loadedBy: ALL_BOTS,
		},
		{
			id: "system-terminal",
			name: "Terminal",
			kind: "application",
			scope: "system",
			tokens: 2600,
			lastWriteAt: "2026-02-20T10:00:00Z",
			loadedBy: ALL_BOTS,
		},
		{
			id: "system-browser",
			name: "Browser",
			kind: "application",
			scope: "system",
			tokens: 3400,
			lastWriteAt: "2026-02-27T14:00:00Z",
			loadedBy: ALL_BOTS,
		},
		{
			id: "system-code-review",
			name: "Code review",
			kind: "skill",
			scope: "system",
			tokens: 1800,
			lastWriteAt: "2026-03-01T09:30:00Z",
			loadedBy: ["bot-atlas", "bot-dorian"],
		},
		{
			id: "user-profile",
			name: "profile.md",
			kind: "file",
			scope: "user",
			tokens: 600,
			lastWriteAt: "2026-03-04T07:30:00Z",
			loadedBy: ALL_BOTS,
		},
		{
			id: "user-writing-style",
			name: "Writing style",
			kind: "skill",
			scope: "user",
			tokens: 900,
			lastWriteAt: "2026-02-10T09:30:00Z",
			loadedBy: ["bot-basile", "bot-clemence"],
		},
		{
			id: "space-notes",
			name: "SPACE.md",
			kind: "file",
			scope: "space",
			tokens: 1500,
			lastWriteAt: "2026-03-03T18:00:00Z",
			loadedBy: ALL_BOTS,
		},
		{
			id: "space-linear",
			name: "Linear",
			kind: "application",
			scope: "space",
			tokens: 2200,
			lastWriteAt: "2026-03-02T09:30:00Z",
			loadedBy: ["bot-atlas", "bot-dorian"],
		},
		{
			id: "space-release-checklist",
			name: "Release checklist",
			kind: "skill",
			scope: "space",
			tokens: 700,
			lastWriteAt: "2026-02-28T09:30:00Z",
			loadedBy: ["bot-basile", "bot-dorian"],
		},
		{
			id: "atlas-persona",
			name: "atlas/persona.md",
			kind: "file",
			scope: "bot",
			tokens: 1200,
			lastWriteAt: "2026-03-04T06:00:00Z",
			loadedBy: ["bot-atlas"],
		},
		{
			id: "atlas-incident-triage",
			name: "Incident triage",
			kind: "skill",
			scope: "bot",
			tokens: 2400,
			lastWriteAt: "2026-03-03T22:00:00Z",
			loadedBy: ["bot-atlas"],
		},
		{
			id: "atlas-grafana",
			name: "Grafana",
			kind: "application",
			scope: "bot",
			tokens: 3100,
			lastWriteAt: "2026-02-25T09:30:00Z",
			loadedBy: ["bot-atlas"],
		},
		{
			id: "basile-persona",
			name: "basile/persona.md",
			kind: "file",
			scope: "bot",
			tokens: 800,
			lastWriteAt: "2026-02-01T09:30:00Z",
			loadedBy: ["bot-basile"],
		},
		{
			id: "basile-changelog",
			name: "Changelog drafting",
			kind: "skill",
			scope: "bot",
			tokens: 1100,
			lastWriteAt: "2026-03-01T15:00:00Z",
			loadedBy: ["bot-basile"],
		},
		{
			id: "clemence-persona",
			name: "clemence/persona.md",
			kind: "file",
			scope: "bot",
			tokens: 950,
			lastWriteAt: "2026-03-04T08:45:00Z",
			loadedBy: ["bot-clemence"],
		},
		{
			id: "clemence-figma",
			name: "Figma",
			kind: "application",
			scope: "bot",
			tokens: 4800,
			lastWriteAt: "2026-03-03T11:00:00Z",
			loadedBy: ["bot-clemence"],
		},
		{
			id: "clemence-design-tokens",
			name: "Design tokens",
			kind: "skill",
			scope: "bot",
			tokens: 1600,
			lastWriteAt: "2026-02-26T09:30:00Z",
			loadedBy: ["bot-clemence"],
		},
		{
			id: "clemence-accessibility",
			name: "Accessibility audit",
			kind: "skill",
			scope: "bot",
			tokens: 1300,
			lastWriteAt: "2026-02-14T09:30:00Z",
			loadedBy: ["bot-clemence"],
		},
		{
			id: "dorian-persona",
			name: "dorian/persona.md",
			kind: "file",
			scope: "bot",
			tokens: 700,
			lastWriteAt: "2026-02-22T09:30:00Z",
			loadedBy: ["bot-dorian"],
		},
		{
			id: "dorian-github",
			name: "GitHub",
			kind: "application",
			scope: "bot",
			tokens: 3900,
			lastWriteAt: "2026-03-04T03:00:00Z",
			loadedBy: ["bot-dorian"],
		},
	],
}

export { SPACE_GRAPH }
