// Generated by tauri-specta from the Rust command surface. Do not edit.
// Run `cargo test --manifest-path apps/app/src-tauri/Cargo.toml --features fake-claude` to regenerate.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	applicationCatalogue: () => typedError<Application_Serialize[], ApplicationsError>(__TAURI_INVOKE("application_catalogue")),
	applicationSearch: (query: string) => typedError<ApplicationSearch_Serialize, ApplicationsError>(__TAURI_INVOKE("application_search", { query })),
	applicationNamed: (name: string) => typedError<{
	name: string,
	title: string,
	description: string,
	config: Json,
	tools?: string[] | null,
	logo?: string | null,
	logoUrl?: string | null,
	useCount?: number | null,
	verified?: boolean | null,
	hostedBy?: string | null,
	categories?: string[],
	authPosture?: AuthPosture | null,
	install: Install_Serialize,
} | null, ApplicationsError>(__TAURI_INVOKE("application_named", { name })),
	applicationInstalls: (conversationId: string) => typedError<ApplicationInstall_Serialize[], ApplicationCallError>(__TAURI_INVOKE("application_installs", { conversationId })),
	applicationRunnable: (config: Json) => __TAURI_INVOKE<{
	field: string,
	reason: string,
} | null>("application_runnable", { config }),
	chatStoreAttachments: (conversationId: string, attachments: SubmittedAttachment[]) => typedError<string[], AttachmentStoreError>(__TAURI_INVOKE("chat_store_attachments", { conversationId, attachments })),
	agentCheck: (scope: {
	conversationId: string,
	botId: string,
	runtimeSessionId: string,
	epoch: number,
} | null) => __TAURI_INVOKE<CheckReport_Serialize>("agent_check", { scope }),
	agentSignIn: () => typedError<null, SignInError>(__TAURI_INVOKE("agent_sign_in")),
	agentSignInCode: (text: string) => typedError<null, SignInError>(__TAURI_INVOKE("agent_sign_in_code", { text })),
	agentSignInCancel: () => typedError<null, SignInError>(__TAURI_INVOKE("agent_sign_in_cancel")),
	agentModels: () => __TAURI_INVOKE<string[]>("agent_models"),
	agentTools: () => __TAURI_INVOKE<string[]>("agent_tools"),
	agentTitle: (text: string) => __TAURI_INVOKE<string | null>("agent_title", { text }),
	agentStartOrResumeSession: (scope: RuntimeScope, resume: string | null, cwd: string | null, outputSchema: null | boolean | number | null | string | Json[] | { [key in string]: Json } | null) => typedError<SessionHandle, TransportError>(__TAURI_INVOKE("agent_start_or_resume_session", { scope, resume, cwd, outputSchema })),
	agentSubmitPrompt: (scope: RuntimeScope, text: string) => typedError<null, TransportError>(__TAURI_INVOKE("agent_submit_prompt", { scope, text })),
	agentCancelTurn: (scope: RuntimeScope) => typedError<null, TransportError>(__TAURI_INVOKE("agent_cancel_turn", { scope })),
	agentRespondToPermission: (scope: RuntimeScope, id: string, decision: PermissionDecision) => typedError<null, TransportError>(__TAURI_INVOKE("agent_respond_to_permission", { scope, id, decision })),
	agentAnswerQuestion: (scope: RuntimeScope, id: string, answers: { [key in string]: string }, annotations: null | boolean | number | null | string | Json[] | { [key in string]: Json } | null) => typedError<null, TransportError>(__TAURI_INVOKE("agent_answer_question", { scope, id, answers, annotations })),
	agentShutdown: (scope: RuntimeScope) => typedError<null, TransportError>(__TAURI_INVOKE("agent_shutdown", { scope })),
	agentLiveSessions: () => typedError<LiveSession[], TransportError>(__TAURI_INVOKE("agent_live_sessions")),
	conversationBots: (spaceId: string | null) => typedError<Bot[], TranscriptStoreError>(__TAURI_INVOKE("conversation_bots", { spaceId })),
	conversationBotsByPresence: (spaceId: string, excludedConversationId: string | null) => typedError<Bot[], TranscriptStoreError>(__TAURI_INVOKE("conversation_bots_by_presence", { spaceId, excludedConversationId })),
	conversationCreateBot: (identity: BotIdentity, spaceId: string | null) => typedError<Bot, TranscriptStoreError>(__TAURI_INVOKE("conversation_create_bot", { identity, spaceId })),
	conversationCreateBotFromDraft: (draft: BotDraft, spaceId: string) => typedError<Bot, TranscriptStoreError>(__TAURI_INVOKE("conversation_create_bot_from_draft", { draft, spaceId })),
	conversationSuggestedBots: () => __TAURI_INVOKE<SuggestedBot[]>("conversation_suggested_bots"),
	companionLaunchOutcome: () => __TAURI_INVOKE<LaunchOutcome>("companion_launch_outcome"),
	conversationDuplicateBot: (botId: string, spaceId: string | null) => typedError<Bot, TranscriptStoreError>(__TAURI_INVOKE("conversation_duplicate_bot", { botId, spaceId })),
	conversationUpdateBot: (id: string, identity: BotIdentity) => typedError<Bot, TranscriptStoreError>(__TAURI_INVOKE("conversation_update_bot", { id, identity })),
	conversationDeleteBot: (id: string) => typedError<null, TranscriptStoreError>(__TAURI_INVOKE("conversation_delete_bot", { id })),
	conversationSetBotAvatarImage: (id: string, bytes: number[]) => typedError<Bot, TranscriptStoreError>(__TAURI_INVOKE("conversation_set_bot_avatar_image", { id, bytes })),
	conversationSetBotMemory: (id: string, memory: string) => typedError<Bot, TranscriptStoreError>(__TAURI_INVOKE("conversation_set_bot_memory", { id, memory })),
	conversationRecordBotCommands: (botId: string, commands: AgentCommand_Deserialize[]) => typedError<null, TranscriptStoreError>(__TAURI_INVOKE("conversation_record_bot_commands", { botId, commands })),
	conversationBotCommands: (botId: string) => typedError<AgentCommand_Serialize[], TranscriptStoreError>(__TAURI_INVOKE("conversation_bot_commands", { botId })),
	conversationMainChat: (botId: string, spaceId: string | null) => typedError<Chat, TranscriptStoreError>(__TAURI_INVOKE("conversation_main_chat", { botId, spaceId })),
	conversationCreate: (spaceId: string, sectionId: string | null, title: string, botIds: string[]) => typedError<Conversation, TranscriptStoreError>(__TAURI_INVOKE("conversation_create", { spaceId, sectionId, title, botIds })),
	conversationList: (spaceId: string) => typedError<Conversation[], TranscriptStoreError>(__TAURI_INVOKE("conversation_list", { spaceId })),
	conversationUpdate: (conversationId: string, title: string, instructions: string, sectionId: string | null) => typedError<Conversation, TranscriptStoreError>(__TAURI_INVOKE("conversation_update", { conversationId, title, instructions, sectionId })),
	conversationDelete: (conversationId: string) => typedError<null, TranscriptStoreError>(__TAURI_INVOKE("conversation_delete", { conversationId })),
	conversationAddParticipant: (conversationId: string, botId: string, invitedByBotId: string | null) => typedError<Conversation, TranscriptStoreError>(__TAURI_INVOKE("conversation_add_participant", { conversationId, botId, invitedByBotId })),
	conversationRemoveParticipant: (conversationId: string, botId: string) => typedError<Conversation, TranscriptStoreError>(__TAURI_INVOKE("conversation_remove_participant", { conversationId, botId })),
	conversationSetLead: (conversationId: string, botId: string) => typedError<Conversation, TranscriptStoreError>(__TAURI_INVOKE("conversation_set_lead", { conversationId, botId })),
	conversationOpenRuntimeSession: (conversationId: string, botId: string, startedAt: number, runtimeSessionId: string | null, reason: string | null) => typedError<RuntimeSession, TranscriptStoreError>(__TAURI_INVOKE("conversation_open_runtime_session", { conversationId, botId, startedAt, runtimeSessionId, reason })),
	conversationRecordProviderSession: (conversationId: string, botId: string, runtimeSessionId: string, providerSessionId: string) => typedError<null, TranscriptStoreError>(__TAURI_INVOKE("conversation_record_provider_session", { conversationId, botId, runtimeSessionId, providerSessionId })),
	conversationBoundedContext: (conversationId: string, botId: string, runtimeSessionId: string, promptMessageId: string) => typedError<string, TranscriptStoreError>(__TAURI_INVOKE("conversation_bounded_context", { conversationId, botId, runtimeSessionId, promptMessageId })),
	conversationRosterBlock: (conversationId: string, botId: string) => typedError<string | null, TranscriptStoreError>(__TAURI_INVOKE("conversation_roster_block", { conversationId, botId })),
	conversationCaptureCheckpoint: (conversationId: string, botId: string, runtimeSessionId: string, createdAt: number) => typedError<{
	id: string,
	conversationId: string,
	botId: string,
	runtimeSessionId: string | null,
	lastMessageSeq: number,
	tokenCount: number,
	createdAt: number,
} | null, TranscriptStoreError>(__TAURI_INVOKE("conversation_capture_checkpoint", { conversationId, botId, runtimeSessionId, createdAt })),
	conversationMessagePage: (conversationId: string, beforeSeq: number | null, limit: number) => typedError<TranscriptPage, TranscriptStoreError>(__TAURI_INVOKE("conversation_message_page", { conversationId, beforeSeq, limit })),
	conversationMessagePageAround: (conversationId: string, seq: number, limit: number) => typedError<TranscriptWindow, TranscriptStoreError>(__TAURI_INVOKE("conversation_message_page_around", { conversationId, seq, limit })),
	conversationMessageReference: (conversationId: string, messageId: string) => typedError<{
	uri: string,
	conversationId: string,
	messageId: string,
	role: TranscriptRole,
	seq: number,
	createdAt: number,
	excerpt: string,
	runtimeSessionId: string | null,
	providerSessionId: string | null,
} | null, TranscriptStoreError>(__TAURI_INVOKE("conversation_message_reference", { conversationId, messageId })),
	conversationPinMessage: (conversationId: string, messageId: string, blockIndex: number, pinnedAt: number) => typedError<null, TranscriptStoreError>(__TAURI_INVOKE("conversation_pin_message", { conversationId, messageId, blockIndex, pinnedAt })),
	conversationUnpinMessage: (conversationId: string, messageId: string, blockIndex: number) => typedError<null, TranscriptStoreError>(__TAURI_INVOKE("conversation_unpin_message", { conversationId, messageId, blockIndex })),
	conversationPinnedMessages: (conversationId: string) => typedError<PinnedBubble[], TranscriptStoreError>(__TAURI_INVOKE("conversation_pinned_messages", { conversationId })),
	conversationStartTurn: (turn: NewTurn) => typedError<number, TranscriptStoreError>(__TAURI_INVOKE("conversation_start_turn", { turn })),
	conversationCompleteTurn: (id: string, completedAt: number) => typedError<null, TranscriptStoreError>(__TAURI_INVOKE("conversation_complete_turn", { id, completedAt })),
	conversationAppendUserMessage: (message: NewUserMessage) => typedError<number, TranscriptStoreError>(__TAURI_INVOKE("conversation_append_user_message", { message })),
	conversationOpenAssistantMessage: (message: NewAssistantMessage) => typedError<number, TranscriptStoreError>(__TAURI_INVOKE("conversation_open_assistant_message", { message })),
	conversationAppendText: (id: string, delta: string) => typedError<null, TranscriptStoreError>(__TAURI_INVOKE("conversation_append_text", { id, delta })),
	conversationFinalizeMessage: (id: string, completion: TerminalCompletion, settledText: string | null) => typedError<null, TranscriptStoreError>(__TAURI_INVOKE("conversation_finalize_message", { id, completion, settledText })),
	envSet: (scope: EnvScope_Deserialize, name: string, value: string) => typedError<null, EnvError>(__TAURI_INVOKE("env_set", { scope, name, value })),
	envDelete: (scope: EnvScope_Deserialize, name: string) => typedError<null, EnvError>(__TAURI_INVOKE("env_delete", { scope, name })),
	envList: (scope: EnvScope_Deserialize) => typedError<EnvEntry_Serialize[], EnvError>(__TAURI_INVOKE("env_list", { scope })),
	connectionSet: (kind: ConnectionKind, value: string) => typedError<null, EnvError>(__TAURI_INVOKE("connection_set", { kind, value })),
	mcpOauthConnect: (owner: EnvOwner, name: string, url: string) => typedError<null, OauthError_Serialize>(__TAURI_INVOKE("mcp_oauth_connect", { owner, name, url })),
	mcpOauthCancel: () => typedError<null, OauthError_Serialize>(__TAURI_INVOKE("mcp_oauth_cancel")),
	mcpOauthDisconnect: (owner: EnvOwner, name: string, url: string) => typedError<Disconnected_Serialize, OauthError_Serialize>(__TAURI_INVOKE("mcp_oauth_disconnect", { owner, name, url })),
	mcpApplicationStatus: (owner: EnvOwner) => typedError<ApplicationRow_Serialize[], EnvError>(__TAURI_INVOKE("mcp_application_status", { owner })),
	missionClose: (missionId: string, closing: MissionClosing) => typedError<Mission, MissionError>(__TAURI_INVOKE("mission_close", { missionId, closing })),
	missionList: (conversationId: string) => typedError<ConversationMissions, MissionError>(__TAURI_INVOKE("mission_list", { conversationId })),
	missionDetail: (missionId: string) => typedError<MissionDetail, MissionError>(__TAURI_INVOKE("mission_detail", { missionId })),
	missionBoard: () => typedError<MissionOnBoard[], MissionError>(__TAURI_INVOKE("mission_board")),
	missionUnreported: () => typedError<MissionOnBoard[], MissionError>(__TAURI_INVOKE("mission_unreported")),
	missionReported: (missionId: string, turnId: string | null) => typedError<Mission, MissionError>(__TAURI_INVOKE("mission_reported", { missionId, turnId })),
	missionAnswered: (missionId: string, seq: number) => typedError<Mission, MissionError>(__TAURI_INVOKE("mission_answered", { missionId, seq })),
	notificationShow: (target: NotificationTarget, title: string, body: string) => __TAURI_INVOKE<void>("notification_show", { target, title, body }),
	pluginSkills: (scope: PluginScope) => typedError<Skill[], TranscriptStoreError>(__TAURI_INVOKE("plugin_skills", { scope })),
	pluginCreateSkill: (scope: PluginScope, draft: SkillDraft) => typedError<Skill, TranscriptStoreError>(__TAURI_INVOKE("plugin_create_skill", { scope, draft })),
	pluginUpdateSkill: (scope: PluginScope, skillId: string, draft: SkillDraft) => typedError<Skill, TranscriptStoreError>(__TAURI_INVOKE("plugin_update_skill", { scope, skillId, draft })),
	pluginSetSkillPreloaded: (scope: PluginScope, skillId: string, isPreloaded: boolean) => typedError<Skill, TranscriptStoreError>(__TAURI_INVOKE("plugin_set_skill_preloaded", { scope, skillId, isPreloaded })),
	pluginDeleteSkill: (scope: PluginScope, skillId: string) => typedError<null, TranscriptStoreError>(__TAURI_INVOKE("plugin_delete_skill", { scope, skillId })),
	pluginSkillFile: (scope: PluginScope, skillId: string, path: string) => typedError<string, TranscriptStoreError>(__TAURI_INVOKE("plugin_skill_file", { scope, skillId, path })),
	pluginWriteSkillFile: (scope: PluginScope, skillId: string, path: string, text: string) => typedError<Skill, TranscriptStoreError>(__TAURI_INVOKE("plugin_write_skill_file", { scope, skillId, path, text })),
	pluginDeleteSkillFile: (scope: PluginScope, skillId: string, path: string) => typedError<null, TranscriptStoreError>(__TAURI_INVOKE("plugin_delete_skill_file", { scope, skillId, path })),
	pluginMcpServers: (scope: PluginScope) => typedError<McpServer_Serialize[], TranscriptStoreError>(__TAURI_INVOKE("plugin_mcp_servers", { scope })),
	pluginSetMcpServer: (scope: PluginScope, name: string, config: Json, mark: {
	title?: string | null,
	logo?: string | null,
	logoUrl?: string | null,
} | null) => typedError<McpServer_Serialize, TranscriptStoreError>(__TAURI_INVOKE("plugin_set_mcp_server", { scope, name, config, mark })),
	pluginDeleteMcpServer: (scope: PluginScope, name: string) => typedError<null, TranscriptStoreError>(__TAURI_INVOKE("plugin_delete_mcp_server", { scope, name })),
	pluginHistory: (scope: PluginScope) => typedError<BotHistoryEntry[], TranscriptStoreError>(__TAURI_INVOKE("plugin_history", { scope })),
	pluginHistoryDiff: (scope: PluginScope, oldestCommitId: string, newestCommitId: string) => typedError<BotChangedFile[], TranscriptStoreError>(__TAURI_INVOKE("plugin_history_diff", { scope, oldestCommitId, newestCommitId })),
	pluginRevert: (scope: PluginScope, oldestCommitId: string, newestCommitId: string) => typedError<BotHistoryEntry[], TranscriptStoreError>(__TAURI_INVOKE("plugin_revert", { scope, oldestCommitId, newestCommitId })),
	routineTriggerSources: (botId: string) => typedError<TriggerSource_Serialize[], TranscriptStoreError>(__TAURI_INVOKE("routine_trigger_sources", { botId })),
	routineCreate: (draft: RoutineDraft_Deserialize) => typedError<Routine_Serialize, RoutineError>(__TAURI_INVOKE("routine_create", { draft })),
	routineUpdate: (id: string, edit: RoutineEdit_Deserialize) => typedError<Routine_Serialize, RoutineError>(__TAURI_INVOKE("routine_update", { id, edit })),
	routineDelete: (id: string) => typedError<null, RoutineError>(__TAURI_INVOKE("routine_delete", { id })),
	routineList: (conversationId: string) => typedError<Routine_Serialize[], RoutineError>(__TAURI_INVOKE("routine_list", { conversationId })),
	routineRuns: (routineId: string, limit: number) => typedError<RoutineRun[], RoutineError>(__TAURI_INVOKE("routine_runs", { routineId, limit })),
	routineReportedRuns: (conversationId: string) => typedError<ReportedRun[], RoutineError>(__TAURI_INVOKE("routine_reported_runs", { conversationId })),
	routineRunNow: (id: string) => typedError<TriggerDecision, RoutineError>(__TAURI_INVOKE("routine_run_now", { id })),
	routineRenewLease: (runId: string) => typedError<null, RoutineError>(__TAURI_INVOKE("routine_renew_lease", { runId })),
	routineCloseRun: (runId: string, closing: RunClosing_Deserialize) => typedError<RoutineRun, RoutineError>(__TAURI_INVOKE("routine_close_run", { runId, closing })),
	routineKey: (id: string) => typedError<RoutineKey_Serialize, RoutineError>(__TAURI_INVOKE("routine_key", { id })),
	searchCatalogue: (query: string, spaceId: string, allSpaces: boolean) => typedError<Catalogue, CatalogueError>(__TAURI_INVOKE("search_catalogue", { query, spaceId, allSpaces })),
	searchMessages: (query: MessageSearchQuery) => typedError<MessageHit[], MessageSearchError>(__TAURI_INVOKE("search_messages", { query })),
	searchRecent: (spaceId: string, allSpaces: boolean) => typedError<CatalogueChat[], CatalogueError>(__TAURI_INVOKE("search_recent", { spaceId, allSpaces })),
	sectionList: (spaceId: string) => typedError<Section[], SectionError>(__TAURI_INVOKE("section_list", { spaceId })),
	sectionCreate: (spaceId: string, name: string) => typedError<Section, SectionError>(__TAURI_INVOKE("section_create", { spaceId, name })),
	sectionRename: (id: string, name: string) => typedError<Section, SectionError>(__TAURI_INVOKE("section_rename", { id, name })),
	rosterPin: (spaceId: string, pins: RosterPin[]) => typedError<null, SectionError>(__TAURI_INVOKE("roster_pin", { spaceId, pins })),
	sectionDelete: (id: string) => typedError<null, SectionError>(__TAURI_INVOKE("section_delete", { id })),
	botMoveToSection: (botId: string, sectionId: string | null, spaceId: string | null) => typedError<null, SectionError>(__TAURI_INVOKE("bot_move_to_section", { botId, sectionId, spaceId })),
	spaceList: () => typedError<Space[], SpaceError>(__TAURI_INVOKE("space_list")),
	spaceCreate: (name: string) => typedError<Space, SpaceError>(__TAURI_INVOKE("space_create", { name })),
	spaceUpdate: (id: string, name: string, colour: "red" | "yellow" | "green" | "cyan" | "blue" | "purple" | "pink" | "orange" | null) => typedError<Space, SpaceError>(__TAURI_INVOKE("space_update", { id, name, colour })),
	spaceReorder: (ids: string[]) => typedError<null, SpaceError>(__TAURI_INVOKE("space_reorder", { ids })),
	spaceDelete: (id: string) => typedError<null, SpaceError>(__TAURI_INVOKE("space_delete", { id })),
	botMoveToSpace: (botId: string, spaceId: string) => typedError<null, SpaceError>(__TAURI_INVOKE("bot_move_to_space", { botId, spaceId })),
	botAddToSpace: (botId: string, spaceId: string, sectionId: string | null) => typedError<null, SpaceError>(__TAURI_INVOKE("bot_add_to_space", { botId, spaceId, sectionId })),
	botRemoveFromSpace: (botId: string, spaceId: string) => typedError<null, SpaceError>(__TAURI_INVOKE("bot_remove_from_space", { botId, spaceId })),
	spacePreferences: (spaceId: string) => typedError<SpacePreferences, SpaceError>(__TAURI_INVOKE("space_preferences", { spaceId })),
	spaceSetPreferences: (spaceId: string, preferences: SpacePreferences) => typedError<SpacePreferences, SpaceError>(__TAURI_INVOKE("space_set_preferences", { spaceId, preferences })),
	userPreferences: () => typedError<UserPreferences, UserPreferencesError>(__TAURI_INVOKE("user_preferences")),
	userSetPreferences: (preferences: UserPreferences) => typedError<UserPreferences, UserPreferencesError>(__TAURI_INVOKE("user_set_preferences", { preferences })),
	userSetProfilePicture: (bytes: number[]) => typedError<UserPreferences, UserPreferencesError>(__TAURI_INVOKE("user_set_profile_picture", { bytes })),
};

/* Types */
export type Account = {
	email: string | null,
	plan: string | null,
};

export type AgentCommand = AgentCommand_Serialize | AgentCommand_Deserialize;

export type AgentCommand_Deserialize = {
	name: string,
	description: string | null,
};

export type AgentCommand_Serialize = {
	name: string,
	description?: string | null,
};

export type Application = Application_Serialize | Application_Deserialize;

export type ApplicationCallError = { kind: "unknownScope"; scope: string } | { kind: "unknownApplication"; application: string } | { kind: "applicationRefused"; application: string; reason: string } | { kind: "conversationWithoutSpace"; conversationId: string } | { kind: "unsearchable"; failure: ApplicationsError } | { kind: "store"; failure: TranscriptStoreError } | { kind: "environment"; failure: EnvError } | { kind: "unreadableRequest"; detail: string } | { kind: "undeliverable"; detail: string } | { kind: "unexpected"; detail: string };

export type ApplicationInstall = ApplicationInstall_Serialize | ApplicationInstall_Deserialize;

export type ApplicationInstall_Deserialize = {
	id: string,
	conversationId: string,
	application: string,
	title: string,
	logo: string | null,
	logoUrl: string | null,
	description: string | null,
	scope: Destination,
	destinationId: string | null,
	install: InstallCase,
	lastMessageSeq: number,
	createdAt: number,
};

export type ApplicationInstall_Serialize = {
	id: string,
	conversationId: string,
	application: string,
	title: string,
	logo?: string | null,
	logoUrl?: string | null,
	description?: string | null,
	scope: Destination,
	destinationId?: string | null,
	install: InstallCase,
	lastMessageSeq: number,
	createdAt: number,
};

export type ApplicationMark = ApplicationMark_Serialize | ApplicationMark_Deserialize;

export type ApplicationMark_Deserialize = {
	title?: string | null,
	logo?: string | null,
	logoUrl?: string | null,
};

export type ApplicationMark_Serialize = {
	title?: string | null,
	logo?: string | null,
	logoUrl?: string | null,
};

export type ApplicationRow = ApplicationRow_Serialize | ApplicationRow_Deserialize;

export type ApplicationRow_Deserialize = {
	name: string,
	scope: EnvScope_Deserialize | null,
} & ApplicationStatus_Deserialize;

export type ApplicationRow_Serialize = {
	name: string,
	scope?: EnvScope_Serialize | null,
} & ApplicationStatus_Serialize;

export type ApplicationSearch = ApplicationSearch_Serialize | ApplicationSearch_Deserialize;

export type ApplicationSearch_Deserialize = {
	applications: Application_Deserialize[],
	registryFailure: ApplicationsError | null,
	readAt: number | null,
	isStale: boolean | null,
};

export type ApplicationSearch_Serialize = {
	applications: Application_Serialize[],
	registryFailure?: ApplicationsError | null,
	readAt?: number | null,
	isStale?: boolean | null,
};

export type ApplicationStatus = ApplicationStatus_Serialize | ApplicationStatus_Deserialize;

export type ApplicationStatus_Deserialize = ({ status: "connected" }) & { reason?: never } | { status: "needsAuthorization"; reason: string | null } | ({ status: "connecting" }) & { reason?: never } | { status: "failed"; reason: string | null } | ({ status: "unknown" }) & { reason?: never };

export type ApplicationStatus_Serialize = ({ status: "connected" }) & { reason?: never } | { status: "needsAuthorization"; reason?: string | null } | ({ status: "connecting" }) & { reason?: never } | { status: "failed"; reason?: string | null } | ({ status: "unknown" }) & { reason?: never };

export type Application_Deserialize = {
	name: string,
	title: string,
	description: string,
	config: Json,
	tools?: string[] | null,
	logo?: string | null,
	logoUrl?: string | null,
	useCount?: number | null,
	verified?: boolean | null,
	hostedBy?: string | null,
	categories?: string[],
	authPosture?: AuthPosture | null,
	install: Install_Deserialize,
};

export type Application_Serialize = {
	name: string,
	title: string,
	description: string,
	config: Json,
	tools?: string[] | null,
	logo?: string | null,
	logoUrl?: string | null,
	useCount?: number | null,
	verified?: boolean | null,
	hostedBy?: string | null,
	categories?: string[],
	authPosture?: AuthPosture | null,
	install: Install_Serialize,
};

export type ApplicationsError = { kind: "catalogueUnreadable"; detail: string } | { kind: "registryUnreached"; detail: string } | { kind: "registryTimedOut" } | { kind: "registryRefused"; status: number } | { kind: "registryUnreadable"; detail: string };

export type AttachmentStoreError = { kind: "unavailable"; failure: StorageFailure } | { kind: "storage"; failure: StorageFailure } | { kind: "unknownConversation"; id: string } | { kind: "tooMany"; count: number; limit: number } | { kind: "tooLarge"; name: string; bytes: number; limit: number } | { kind: "tooLargeTogether"; bytes: number; limit: number } | { kind: "unwritable"; detail: string };

export type AuthPosture = "authRequired" | "noAuth";

export type AuthorizationWithheld = "servedOverNoUrl" | "loopbackAddress" | "ownAuthorizationHeader" | "unexpandedPlaceholder";

export type AvatarAnimal = "rabbit" | "cat" | "bear" | "chick" | "dog" | "mouse" | "owl" | "koala";

export type AvatarBlot = "red" | "yellow" | "green" | "cyan" | "blue" | "purple" | "pink" | "orange";

export type AvatarRejection = { kind: "unknownFormat" } | { kind: "tooLarge"; bytes: number; limit: number } | { kind: "undecodable"; detail: string } | { kind: "unwritable"; detail: string };

export type Bot = {
	id: string,
	sectionId: string | null,
	pinPosition: number | null,
	name: string,
	title: string,
	model: string,
	avatarAnimal: AvatarAnimal,
	avatarBlot: AvatarBlot | null,
	avatarImagePath: string | null,
	workingDir: string | null,
	instructions: string,
	memory: string,
	deniedTools: string[],
	changesNothing: boolean,
	permissions: BotPermissions,
	outputStyle: string,
	createdAt: number,
};

export type BotChangedFile = {
	path: string,
	previousPath: string | null,
	change: HistoryFileChange,
	patch: string,
};

export type BotDraft = {
	name: string,
	job: string,
	description: string,
};

export type BotHistoryEntry = {
	id: string,
	timestamp: number,
	author: HistoryAuthor,
	title: string,
	body: string,
	paths: string[],
};

export type BotIdentity = {
	name: string,
	title: string,
	model: string,
	avatarAnimal: AvatarAnimal,
	avatarBlot: AvatarBlot | null,
	avatarImagePath: string | null,
	workingDir: string | null,
	instructions: string,
	deniedTools: string[],
	permissions?: BotPermissions,
	outputStyle?: string,
};

export type BotPermissions = {
	defaultMode: string,
	allow: string[],
	ask: string[],
	deny: string[],
};

export type Catalogue = {
	chats: CatalogueChat[],
	missions: CatalogueMission[],
	routines: CatalogueRoutine[],
};

export type CatalogueChat = {
	conversationId: string,
	kind: ConversationKind,
	title: string,
	botId: string | null,
	participants: string[],
	spaceId: string | null,
};

export type CatalogueError = { kind: "unavailable"; failure: StorageFailure } | { kind: "storage"; failure: StorageFailure } | { kind: "queryTooLong"; limit: number } | { kind: "unknownBot"; id: string };

export type CatalogueMission = {
	id: string,
	threadConversationId: string,
	objective: string,
	ticketPlatform: string,
	ticketExternalId: string,
	ticketTitle: string,
	state: MissionState,
	botId: string,
	spaceId: string,
};

export type CatalogueRoutine = {
	id: string,
	conversationId: string,
	botId: string,
	title: string,
	triggerSourceId: string,
	isEnabled: boolean,
	expression: string | null,
	spaceId: string,
};

export type Chat = {
	id: string,
	createdAt: number,
	updatedAt: number,
};

export type CheckReport = CheckReport_Serialize | CheckReport_Deserialize;

export type CheckReport_Deserialize = {
	connection: ConnectionState,
	binaryVersion: string | null,
	authenticated: boolean,
	authMethod?: string | null,
	error: TransportError | null,
	account?: Account | null,
};

export type CheckReport_Serialize = {
	connection: ConnectionState,
	binaryVersion: string | null,
	authenticated: boolean,
	authMethod?: string | null,
	error: TransportError | null,
	account?: Account | null,
};

export type ColorScheme = "system" | "light" | "dark";

export type CompanionArrival = {
	id: string,
	conversationId: string,
	botId: string,
	invitedByBotId: string | null,
	lastMessageSeq: number,
	createdAt: number,
};

export type CompanionCreated = {
	id: string,
	name: string,
};

export type CompanionSeedRefused = {
	reason: string,
};

export type ConnectionKind = "apiKey" | "subscriptionToken";

export type ConnectionState = "checking" | "ready" | "unavailable" | "crashed";

export type ContextCheckpoint = {
	id: string,
	conversationId: string,
	botId: string,
	runtimeSessionId: string | null,
	lastMessageSeq: number,
	tokenCount: number,
	createdAt: number,
};

export type Conversation = {
	id: string,
	spaceId: string | null,
	sectionId: string | null,
	pinPosition: number | null,
	title: string,
	instructions: string,
	createdAt: number,
	updatedAt: number,
	participants: Participant[],
};

export type ConversationKind = "main" | "topic" | "mission";

export type ConversationMissions = {
	open: Mission[],
	done: Mission[],
};

export type Destination = "companion" | "space" | "user";

export type Disconnected = Disconnected_Serialize | Disconnected_Deserialize;

export type Disconnected_Deserialize = {
	revoked: boolean,
	detail: string | null,
};

export type Disconnected_Serialize = {
	revoked: boolean,
	detail?: string | null,
};

export type EnvEntry = EnvEntry_Serialize | EnvEntry_Deserialize;

export type EnvEntry_Deserialize = {
	name: string,
	definedIn: EnvScope_Deserialize,
	servedFrom: EnvScope_Deserialize,
};

export type EnvEntry_Serialize = {
	name: string,
	definedIn: EnvScope_Serialize,
	servedFrom: EnvScope_Serialize,
};

export type EnvError = { kind: "invalidName"; name: string } | { kind: "invalidScope"; detail: string } | { kind: "unreadable"; detail: string } | { kind: "unwritable"; detail: string } | { kind: "emptyValue" };

export type EnvOwner = { kind: "user" } | { kind: "space"; id: string } | { kind: "bot"; id: string; spaceId: string };

export type EnvScope = EnvScope_Serialize | EnvScope_Deserialize;

export type EnvScope_Deserialize = ({ kind: "user" }) & { id?: never; name?: never; owner?: never; spaceId?: never } | ({ kind: "space"; id: string }) & { name?: never; owner?: never; spaceId?: never } | ({ kind: "bot"; id: string; spaceId: string }) & { name?: never; owner?: never } | ({ kind: "server"; name: string; owner: EnvOwner }) & { id?: never; spaceId?: never };

export type EnvScope_Serialize = ({ kind: "user" }) & { id?: never; name?: never; owner?: never; spaceId?: never } | ({ kind: "space"; id: string }) & { name?: never; owner?: never; spaceId?: never } | ({ kind: "bot"; id: string; spaceId: string }) & { name?: never; owner?: never } | ({ kind: "server"; name: string; owner: EnvOwner }) & { id?: never; spaceId?: never } | ({ kind: "person" }) & { id?: never; name?: never; owner?: never; spaceId?: never };

export type FieldType = "string" | "number" | "boolean" | "datetime";

export type Filter = Filter_Serialize | Filter_Deserialize;

export type FilterMatchMode = "all" | "any";

export type FilterOperator = "exists" | "not_exists" | "equals" | "not_equals" | "contains" | "not_contains" | "starts_with" | "ends_with" | "gt" | "lt";

export type FilterRow = FilterRow_Serialize | FilterRow_Deserialize;

export type FilterRow_Deserialize = {
	field: string,
	operator: FilterOperator,
	value?: Json | null,
};

export type FilterRow_Serialize = {
	field: string,
	operator: FilterOperator,
	value?: Json | null,
};

export type Filter_Deserialize = {
	matchMode: FilterMatchMode,
	rows: FilterRow_Deserialize[],
};

export type Filter_Serialize = {
	matchMode: FilterMatchMode,
	rows: FilterRow_Serialize[],
};

export type HistoryAuthor = "user" | "bot";

export type HistoryFileChange = "added" | "modified" | "deleted" | "renamed";

export type Install = Install_Serialize | Install_Deserialize;

export type InstallCase = { kind: "nothing" } | { kind: "key"; secrets: string[] } | { kind: "oauth" };

export type InstallField = InstallField_Serialize | InstallField_Deserialize;

export type InstallField_Deserialize = {
	name: string,
	secret: string,
	description?: string | null,
	concealed?: boolean,
};

export type InstallField_Serialize = {
	name: string,
	secret: string,
	description?: string | null,
	concealed: boolean,
};

export type InstallRefusal = {
	field: string,
	reason: string,
};

export type Install_Deserialize = ({ nothing: {
	kind: "nothing",
} }) & { key?: never; oauth?: never; refused?: never } | ({ key: {
	kind: "key",
	fields: InstallField_Deserialize[],
} }) & { nothing?: never; oauth?: never; refused?: never } | ({ oauth: {
	kind: "oauth",
} }) & { key?: never; nothing?: never; refused?: never } | ({ refused: {
	kind: "refused",
} & InstallRefusal }) & { key?: never; nothing?: never; oauth?: never };

export type Install_Serialize = ({ nothing: {
	kind: "nothing",
} }) & { key?: never; oauth?: never; refused?: never } | ({ key: {
	kind: "key",
	fields: InstallField_Serialize[],
} }) & { nothing?: never; oauth?: never; refused?: never } | ({ oauth: {
	kind: "oauth",
} }) & { key?: never; nothing?: never; refused?: never } | ({ refused: {
	kind: "refused",
} & InstallRefusal }) & { key?: never; nothing?: never; oauth?: never };

export type Json = null | boolean | number | null | string | Json[] | { [key in string]: Json };

export type LaunchOutcome = {
	created: CompanionCreated | null,
	refused: CompanionSeedRefused | null,
};

export type LiveSession = {
	botId: string,
	conversationId: string,
	runtimeSessionId: string,
	startedAt: number,
};

export type McpServer = McpServer_Serialize | McpServer_Deserialize;

export type McpServer_Deserialize = {
	name: string,
	config: Json,
} & ApplicationMark_Deserialize;

export type McpServer_Serialize = {
	name: string,
	config: Json,
} & ApplicationMark_Serialize;

export type MessageHit = {
	messageId: string,
	seq: number,
	conversationId: string,
	conversationKind: ConversationKind,
	conversationTitle: string,
	authorBotId: string | null,
	createdAt: number,
	spaceId: string | null,
	snippet: SnippetPart[],
};

export type MessageReference = {
	uri: string,
	conversationId: string,
	messageId: string,
	role: TranscriptRole,
	seq: number,
	createdAt: number,
	excerpt: string,
	runtimeSessionId: string | null,
	providerSessionId: string | null,
};

export type MessageSearchError = { kind: "unavailable"; failure: StorageFailure } | { kind: "storage"; failure: StorageFailure } | { kind: "queryTooLong"; limit: number };

export type MessageSearchQuery = {
	text: string,
	spaceId: string,
	allSpaces: boolean,
};

export type Mission = {
	id: string,
	originConversationId: string,
	botId: string,
	threadConversationId: string,
	objective: string,
	ticket: Ticket,
	tools: string[],
	state: MissionState,
	stateSeq: number,
	openedAt: number,
	closedAt: number | null,
	reportedAt: number | null,
	reportedTurnId: string | null,
};

export type MissionClosing = {
	source: string,
	outcome: MissionOutcome,
	summary: string,
};

export type MissionDetail = {
	mission: Mission,
	events: MissionEvent[],
};

export type MissionDraft = {
	originConversationId: string,
	botId: string,
	objective: string,
	ticket: Ticket,
	tools: string[],
	source: string,
	workspacePath?: string | null,
};

export type MissionEntry = {
	kind: MissionEventKind,
	source: string,
	payload: Json,
};

export type MissionError = { kind: "unavailable"; failure: StorageFailure } | { kind: "storage"; failure: StorageFailure } | { kind: "unknownMission"; id: string } | { kind: "unknownConversation"; id: string } | { kind: "missionAlreadyClosed"; id: string } | { kind: "missionStillOpen"; id: string } | { kind: "missionAlreadyReported"; id: string } | { kind: "unknownTurn"; id: string } | { kind: "turnOfAnotherConversation"; turnId: string; conversationId: string } | { kind: "unknownBot"; id: string } | { kind: "unknownParticipant"; conversationId: string; botId: string } | { kind: "blankField"; field: string } | { kind: "missionOfAnotherConversation"; id: string; conversationId: string } | { kind: "missionOfAnotherBot"; id: string; botId: string } | { kind: "unreadableRequest"; detail: string } | { kind: "undeliverable"; detail: string } | { kind: "unexpected"; detail: string };

export type MissionEvent = {
	id: string,
	missionId: string,
	kind: MissionEventKind,
	source: string,
	payload: Json,
	createdAt: number,
};

export type MissionEventKind = "opened" | "note" | "agent_asked" | "answered" | "escalated" | "ready" | "checks_failed" | "failed" | "closed";

export type MissionNote = {
	source: string,
	payload: Json,
};

export type MissionOnBoard = {
	mission: Mission,
	bot: Bot,
};

export type MissionOutcome = "done" | "failed";

export type MissionState = "working" | "waiting_bot" | "waiting_human" | "ready_to_merge" | "failed" | "done";

export type NewAssistantMessage = {
	id: string,
	conversationId: string,
	turnId: string,
	authorBotId: string | null,
	repliedToMessageId: string | null,
	createdAt: number,
};

export type NewTurn = {
	id: string,
	conversationId: string,
	startedAt: number,
};

export type NewUserMessage = {
	id: string,
	conversationId: string,
	turnId: string,
	authorBotId: string | null,
	repliedToMessageId: string | null,
	content: string,
	createdAt: number,
};

export type NotificationTarget = {
	kind: string,
	id: string,
};

export type OauthError = OauthError_Serialize | OauthError_Deserialize;

export type OauthError_Deserialize = ({ kind: "alreadyRunning" }) & { body?: never; carries?: never; detail?: never; error?: never; status?: never; step?: never; timeoutMs?: never; url?: never } | ({ kind: "cancelled" }) & { body?: never; carries?: never; detail?: never; error?: never; status?: never; step?: never; timeoutMs?: never; url?: never } | ({ kind: "timedOut" }) & { body?: never; carries?: never; detail?: never; error?: never; status?: never; step?: never; timeoutMs?: never; url?: never } | ({ kind: "denied"; detail: string }) & { body?: never; carries?: never; error?: never; status?: never; step?: never; timeoutMs?: never; url?: never } | ({ kind: "browserRefused"; url: string }) & { body?: never; carries?: never; detail?: never; error?: never; status?: never; step?: never; timeoutMs?: never } | ({ kind: "notAuthorizable"; carries: AuthorizationWithheld; detail: string }) & { body?: never; error?: never; status?: never; step?: never; timeoutMs?: never; url?: never } | ({ kind: "refusedUrl"; url: string }) & { body?: never; carries?: never; detail?: never; error?: never; status?: never; step?: never; timeoutMs?: never } | ({ kind: "flowTimedOut"; timeoutMs: number }) & { body?: never; carries?: never; detail?: never; error?: never; status?: never; step?: never; url?: never } | ({ kind: "failed"; detail: string; step: OauthStep | null; status: number | null; body: string | null }) & { carries?: never; error?: never; timeoutMs?: never; url?: never } | ({ kind: "transport"; error: TransportError }) & { body?: never; carries?: never; detail?: never; status?: never; step?: never; timeoutMs?: never; url?: never } | ({ kind: "store"; error: EnvError }) & { body?: never; carries?: never; detail?: never; status?: never; step?: never; timeoutMs?: never; url?: never };

export type OauthError_Serialize = ({ kind: "alreadyRunning" }) & { body?: never; carries?: never; detail?: never; error?: never; status?: never; step?: never; timeoutMs?: never; url?: never } | ({ kind: "cancelled" }) & { body?: never; carries?: never; detail?: never; error?: never; status?: never; step?: never; timeoutMs?: never; url?: never } | ({ kind: "timedOut" }) & { body?: never; carries?: never; detail?: never; error?: never; status?: never; step?: never; timeoutMs?: never; url?: never } | ({ kind: "denied"; detail: string }) & { body?: never; carries?: never; error?: never; status?: never; step?: never; timeoutMs?: never; url?: never } | ({ kind: "browserRefused"; url: string }) & { body?: never; carries?: never; detail?: never; error?: never; status?: never; step?: never; timeoutMs?: never } | ({ kind: "notAuthorizable"; carries: AuthorizationWithheld; detail: string }) & { body?: never; error?: never; status?: never; step?: never; timeoutMs?: never; url?: never } | ({ kind: "refusedUrl"; url: string }) & { body?: never; carries?: never; detail?: never; error?: never; status?: never; step?: never; timeoutMs?: never } | ({ kind: "flowTimedOut"; timeoutMs: number }) & { body?: never; carries?: never; detail?: never; error?: never; status?: never; step?: never; url?: never } | ({ kind: "failed"; detail: string; step?: OauthStep | null; status?: number | null; body?: string | null }) & { carries?: never; error?: never; timeoutMs?: never; url?: never } | ({ kind: "transport"; error: TransportError }) & { body?: never; carries?: never; detail?: never; status?: never; step?: never; timeoutMs?: never; url?: never } | ({ kind: "store"; error: EnvError }) & { body?: never; carries?: never; detail?: never; status?: never; step?: never; timeoutMs?: never; url?: never };

export type OauthStep = "discovery" | "registration" | "tokenExchange";

export type Participant = {
	botId: string,
	role: ParticipantRole,
	joinedAt: number,
	leftAt: number | null,
	name: string,
	avatarAnimal: AvatarAnimal,
	avatarBlot: AvatarBlot | null,
	avatarImagePath: string | null,
	isDeleted: boolean,
};

export type ParticipantRole = "lead" | "assistant";

export type PayloadField = {
	name: string,
	type: FieldType,
};

export type PermissionDecision = "allowOnce" | "deny";

export type PinnedBubble = {
	message: TranscriptMessage,
	blockIndex: number,
	pinnedAt: number,
};

export type PluginScope = { kind: "bot"; id: string } | { kind: "space"; id: string } | { kind: "user" };

export type Refusal = "disabled" | "filter" | "dedupeValueMissing" | "alreadySeen";

export type ReportedRun = {
	turnId: string,
	routineTitle: string,
	triggerSourceId: string,
};

export type RosterPin = {
	id: string,
	sectionId: string | null,
};

export type Routine = Routine_Serialize | Routine_Deserialize;

export type RoutineDraft = RoutineDraft_Serialize | RoutineDraft_Deserialize;

export type RoutineDraft_Deserialize = {
	conversationId: string,
	botId: string,
	title: string,
	instruction: string,
	triggerSourceId: string,
	filter: Filter_Deserialize,
	triggerConfig: Json,
};

export type RoutineDraft_Serialize = {
	conversationId: string,
	botId: string,
	title: string,
	instruction: string,
	triggerSourceId: string,
	filter: Filter_Serialize,
	triggerConfig: Json,
};

export type RoutineEdit = RoutineEdit_Serialize | RoutineEdit_Deserialize;

export type RoutineEdit_Deserialize = {
	title: string,
	instruction: string,
	filter: Filter_Deserialize,
	triggerConfig: Json,
	isEnabled: boolean,
};

export type RoutineEdit_Serialize = {
	title: string,
	instruction: string,
	filter: Filter_Serialize,
	triggerConfig: Json,
	isEnabled: boolean,
};

export type RoutineError = { kind: "unavailable"; failure: StorageFailure } | { kind: "storage"; failure: StorageFailure } | { kind: "unknownRoutine"; id: string } | { kind: "unknownRun"; id: string } | { kind: "unknownBot"; id: string } | { kind: "unknownParticipant"; conversationId: string; botId: string } | { kind: "unknownSource"; id: string } | { kind: "routineOfAnotherConversation"; id: string; conversationId: string } | { kind: "routineOfAnotherBot"; id: string; botId: string } | { kind: "unreadableRequest"; detail: string } | { kind: "unknownTurn"; id: string } | { kind: "turnOfAnotherConversation"; turnId: string; conversationId: string } | { kind: "turnAlreadyReported"; turnId: string; runId: string } | { kind: "turnWithoutReport"; turnId: string; outcome: RunOutcome } | { kind: "blankField"; field: string } | { kind: "unsupportedOperator"; row: number; field: string; operator: FilterOperator; fieldType: FieldType } | { kind: "runAlreadyClosed"; id: string } | { kind: "unreadableSources"; path: string; reason: string } | { kind: "unreadableExpression"; expression: string; reason: string } | { kind: "undeliverable"; detail: string } | { kind: "unexpected"; detail: string };

export type RoutineKey = RoutineKey_Serialize | RoutineKey_Deserialize;

export type RoutineKey_Deserialize = {
	key: string,
	header?: string | null,
	url?: string | null,
};

export type RoutineKey_Serialize = {
	key: string,
	header?: string | null,
	url?: string | null,
};

export type RoutineRun = {
	id: string,
	routineId: string,
	startedAt: number,
	endedAt: number | null,
	outcome: RunOutcome | null,
	reason: string | null,
	costUsd: number | null,
	modelUsage: Json | null,
};

export type Routine_Deserialize = {
	id: string,
	conversationId: string,
	botId: string,
	title: string,
	instruction: string,
	triggerSourceId: string,
	filter: Filter_Deserialize,
	triggerConfig: Json,
	isEnabled: boolean,
	consecutiveFailures: number,
	createdAt: number,
};

export type Routine_Serialize = {
	id: string,
	conversationId: string,
	botId: string,
	title: string,
	instruction: string,
	triggerSourceId: string,
	filter: Filter_Serialize,
	triggerConfig: Json,
	isEnabled: boolean,
	consecutiveFailures: number,
	createdAt: number,
};

export type RunCause = "trigger" | "runNow";

export type RunClosing = RunClosing_Serialize | RunClosing_Deserialize;

export type RunClosing_Deserialize = {
	outcome: RunOutcome,
	reason?: string | null,
	costUsd?: number | null,
	modelUsage?: Json | null,
	reportedTurnId?: string | null,
};

export type RunClosing_Serialize = {
	outcome: RunOutcome,
	reason?: string | null,
	costUsd?: number | null,
	modelUsage?: Json | null,
	reportedTurnId?: string | null,
};

export type RunOutcome = "ok" | "nothing" | "skipped" | "failed";

export type RunRequested = {
	cause: RunCause,
	title: string,
	instruction: string,
	routineId: string,
	runId: string,
	botId: string,
	conversationId: string,
	triggerSourceId: string,
	payload: Json,
};

export type RuntimeScope = {
	conversationId: string,
	botId: string,
	runtimeSessionId: string,
	epoch: number,
};

export type RuntimeSession = {
	id: string,
	conversationId: string,
	botId: string,
	seq: number,
	startedAt: number,
};

export type Section = {
	id: string,
	spaceId: string,
	name: string,
	position: number,
	createdAt: number,
};

export type SectionError = { kind: "unavailable"; failure: StorageFailure } | { kind: "storage"; failure: StorageFailure } | { kind: "unknownSection"; id: string } | { kind: "unknownBot"; id: string } | { kind: "severalSpaces"; id: string } | { kind: "foreignSpace"; id: string } | { kind: "foreignSection"; id: string };

export type SessionHandle = {
	resumed: boolean,
};

export type SignInError = { kind: "alreadyRunning" } | { kind: "notRunning" } | { kind: "cancelled" } | { kind: "timedOut" } | { kind: "refusedUrl"; url: string } | { kind: "flowTimedOut"; timeoutMs: number } | { kind: "failed"; detail: string } | { kind: "transport"; error: TransportError };

export type Skill = {
	id: string,
	name: string,
	description: string,
	body: string,
	isPreloaded: boolean,
	isSystem: boolean,
	files: string[],
} & SkillFront;

export type SkillDraft = {
	name: string,
	description: string,
	body: string,
} & SkillFront;

export type SkillFront = {
	whenToUse?: string | null,
	argumentHint?: string | null,
	arguments?: string[] | null,
	disableModelInvocation?: boolean | null,
	userInvocable?: boolean | null,
	allowedTools?: string[] | null,
	disallowedTools?: string[] | null,
	model?: string | null,
	effort?: string | null,
	context?: string | null,
	agent?: string | null,
	background?: boolean | null,
	hooks?: Json | null,
	paths?: string[] | null,
	shell?: string | null,
	metadata?: Json | null,
	license?: string | null,
	compatibility?: Json | null,
};

export type SkipReason = "leaseHeld" | "hourlyCap" | "backingOff";

export type SnippetPart = {
	text: string,
	matched: boolean,
};

export type Space = {
	id: string,
	name: string,
	colour: AvatarBlot | null,
	position: number,
	createdAt: number,
};

export type SpaceError = { kind: "unavailable"; failure: StorageFailure } | { kind: "storage"; failure: StorageFailure } | { kind: "unknownSpace"; id: string } | { kind: "unknownBot"; id: string } | { kind: "unwritableBundle"; detail: string } | { kind: "incompleteOrder" } | { kind: "lastSpace" } | { kind: "lastSpaceOfBot"; id: string } | { kind: "foreignSection"; id: string };

export type SpacePreferences = {
	collapsedSectionIds?: string[],
};

export type StorageFailure = { kind: "appDataDir" } | { kind: "journalMode"; mode: string } | { kind: "poisonedConnection" } | { kind: "callInterrupted" } | { kind: "staleWrite" } | { kind: "sqlite"; detail: string };

export type SubmittedAttachment = {
	name: string,
	bytes: number[],
};

export type SuggestedBot = {
	id: string,
	name: string,
	job: string,
	description: string,
	blurb: string,
};

export type TerminalCompletion = "complete" | "cancelled" | "failed" | "interrupted";

export type Ticket = {
	platform: string,
	externalId: string,
	url: string,
	title: string,
};

export type TranscriptCompletion = "pending" | "streaming" | "complete" | "cancelled" | "failed" | "interrupted";

export type TranscriptMessage = {
	id: string,
	conversationId: string,
	turnId: string,
	seq: number,
	role: TranscriptRole,
	content: string,
	completion: TranscriptCompletion,
	createdAt: number,
	authorBotId: string | null,
	repliedToMessageId: string | null,
	runtimeSessionId: string | null,
};

export type TranscriptPage = {
	conversationId: string,
	messages: TranscriptMessage[],
	arrivals: CompanionArrival[],
	hasMore: boolean,
};

export type TranscriptRole = "user" | "assistant";

export type TranscriptStoreError = { kind: "unavailable"; failure: StorageFailure } | { kind: "storage"; failure: StorageFailure } | { kind: "conflict"; id: string; field: string } | { kind: "invalidTransition"; id: string; from: string; to: string } | { kind: "unknownBot"; id: string } | { kind: "namelessBot" } | { kind: "unknownConversation"; id: string } | { kind: "foreignBot"; id: string } | { kind: "severalSpaces"; id: string } | { kind: "unknownParticipant"; conversationId: string; botId: string } | { kind: "unknownMessage"; id: string } | { kind: "unknownMessageSeq"; conversationId: string; seq: number } | { kind: "rejectedAvatarImage"; reason: AvatarRejection } | { kind: "unwritableBundle"; detail: string } | { kind: "unwritableEnvironment"; failure: EnvError } | { kind: "systemSkill"; id: string } | { kind: "unreadableHistory"; detail: string } | { kind: "unreadableSources"; path: string; reason: string };

export type TranscriptWindow = {
	conversationId: string,
	messages: TranscriptMessage[],
	arrivals: CompanionArrival[],
	hasOlder: boolean,
	hasNewer: boolean,
};

export type TransportError = { kind: "binaryNotFound"; searched: string[] } | { kind: "notAuthenticated" } | { kind: "authCheckFailed"; detail: string } | { kind: "spawnFailed"; detail: string } | { kind: "startupTimeout"; timeoutMs: number } | { kind: "crashed"; code: number | null; detail: string | null } | { kind: "resumeFailed"; forgotSessionId: boolean } | { kind: "workingDirectoryRefused"; path: string } | { kind: "invalidFrame"; detail: string } | { kind: "settingsRejected"; detail: string } | { kind: "serverEnvRejected"; detail: string } | { kind: "notStarted" } | { kind: "turnAlreadyRunning" } | { kind: "transitionInProgress" } | { kind: "noActiveTurn" } | { kind: "staleRuntimeSession"; runtimeSessionId: string } | { kind: "unknownPermission"; id: string } | { kind: "writeFailed"; detail: string };

export type TriggerDecision = { kind: "started"; runId: string } | { kind: "skipped"; runId: string; reason: SkipReason } | { kind: "refused"; by: Refusal };

export type TriggerEvent = TriggerEvent_Serialize | TriggerEvent_Deserialize;

export type TriggerEvent_Deserialize = {
	routineId: string,
	source: TriggerSource_Deserialize,
	payload: Json,
};

export type TriggerEvent_Serialize = {
	routineId: string,
	source: TriggerSource_Serialize,
	payload: Json,
};

export type TriggerSource = TriggerSource_Serialize | TriggerSource_Deserialize;

export type TriggerSource_Deserialize = {
	id: string,
	title: string,
	payload: PayloadField[],
	dedupeKey: string,
	header?: string | null,
};

export type TriggerSource_Serialize = {
	id: string,
	title: string,
	payload: PayloadField[],
	dedupeKey: string,
	header?: string | null,
};

export type UserPreferences = {
	displayName: string,
	profilePicturePath: string | null,
	colorScheme: ColorScheme,
	language: string | null,
	notifyOnQuestion: boolean,
	notifyOnPermission: boolean,
	notifyOnFinishedTurn: boolean,
	notifyWithSound: boolean,
	sidebarWidth: number | null,
	activityPanelOpen?: boolean,
	firstRunDone?: boolean,
	lastSpaceId: string | null,
	lastBotIdBySpace?: { [key in string]: string },
};

export type UserPreferencesError = { kind: "unavailable"; failure: StorageFailure } | { kind: "storage"; failure: StorageFailure } | { kind: "rejectedProfilePicture"; reason: AvatarRejection };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

