use tauri::{ipc::Invoke, Runtime};
use tauri_specta::{collect_commands, Builder, Commands};

use crate::{
	agent, applications, attachments, companions, conversations, environment, mcp_oauth, missions,
	notifications, plugins, routines, search, sections, spaces, user,
};

pub fn builder() -> Builder<tauri::Wry> {
	Builder::new().commands(commands())
}

// `tauri::test::mock_builder` only ever yields a `Builder<MockRuntime>`, so the handler the
// integration tests mount cannot come from the `tauri::Wry` builder the exporter needs.
pub fn invoke_handler<R: Runtime>() -> impl Fn(Invoke<R>) -> bool + Send + Sync + 'static {
	let builder = Builder::<R>::new().commands(commands());
	move |invoke| builder.invoke_handler()(invoke)
}

fn commands<R: Runtime>() -> Commands<R> {
	collect_commands![
		applications::commands::application_catalogue,
		applications::commands::application_search,
		applications::commands::application_named,
		applications::commands::application_installs,
		applications::commands::application_runnable,
		attachments::commands::chat_store_attachments::<tauri::Wry>,
		agent::commands::agent_check::<tauri::Wry>,
		agent::sign_in::agent_sign_in::<tauri::Wry>,
		agent::sign_in::agent_sign_in_code::<tauri::Wry>,
		agent::sign_in::agent_sign_in_cancel::<tauri::Wry>,
		agent::commands::agent_models::<tauri::Wry>,
		agent::commands::agent_tools::<tauri::Wry>,
		agent::commands::agent_title::<tauri::Wry>,
		agent::commands::agent_start_or_resume_session::<tauri::Wry>,
		agent::commands::agent_submit_prompt,
		agent::commands::agent_cancel_turn,
		agent::commands::agent_respond_to_permission,
		agent::commands::agent_answer_question,
		agent::commands::agent_shutdown::<tauri::Wry>,
		agent::commands::agent_live_sessions,
		conversations::commands::conversation_bots::<tauri::Wry>,
		conversations::commands::conversation_bots_by_presence::<tauri::Wry>,
		conversations::commands::conversation_create_bot::<tauri::Wry>,
		conversations::commands::conversation_create_bot_from_draft::<tauri::Wry>,
		conversations::commands::conversation_suggested_bots,
		companions::launch::companion_launch_outcome,
		conversations::commands::conversation_duplicate_bot::<tauri::Wry>,
		conversations::commands::conversation_update_bot::<tauri::Wry>,
		conversations::commands::conversation_delete_bot::<tauri::Wry>,
		conversations::commands::conversation_set_bot_avatar_image::<tauri::Wry>,
		conversations::commands::conversation_set_bot_memory::<tauri::Wry>,
		conversations::commands::conversation_record_bot_commands,
		conversations::commands::conversation_bot_commands,
		conversations::commands::conversation_main_chat,
		conversations::commands::conversation_create::<tauri::Wry>,
		conversations::commands::conversation_list::<tauri::Wry>,
		conversations::commands::conversation_update::<tauri::Wry>,
		conversations::commands::conversation_delete,
		conversations::commands::conversation_add_participant::<tauri::Wry>,
		conversations::commands::conversation_remove_participant::<tauri::Wry>,
		conversations::commands::conversation_set_lead::<tauri::Wry>,
		conversations::commands::conversation_open_runtime_session,
		conversations::commands::conversation_record_provider_session,
		conversations::commands::conversation_bounded_context,
		conversations::commands::conversation_roster_block,
		conversations::commands::conversation_capture_checkpoint,
		conversations::commands::conversation_message_page,
		conversations::commands::conversation_message_page_around,
		conversations::commands::conversation_message_reference,
		conversations::commands::conversation_pin_message,
		conversations::commands::conversation_unpin_message,
		conversations::commands::conversation_pinned_messages,
		conversations::commands::conversation_start_turn,
		conversations::commands::conversation_complete_turn,
		conversations::commands::conversation_append_user_message,
		conversations::commands::conversation_open_assistant_message,
		conversations::commands::conversation_append_text,
		conversations::commands::conversation_finalize_message,
		environment::commands::env_set::<tauri::Wry>,
		environment::commands::env_delete::<tauri::Wry>,
		environment::commands::env_list::<tauri::Wry>,
		environment::commands::connection_set::<tauri::Wry>,
		mcp_oauth::commands::mcp_oauth_connect::<tauri::Wry>,
		mcp_oauth::commands::mcp_oauth_cancel::<tauri::Wry>,
		mcp_oauth::commands::mcp_oauth_disconnect::<tauri::Wry>,
		mcp_oauth::commands::mcp_application_status::<tauri::Wry>,
		missions::commands::mission_close::<tauri::Wry>,
		missions::commands::mission_list,
		missions::commands::mission_detail,
		missions::commands::mission_board::<tauri::Wry>,
		missions::commands::mission_unreported::<tauri::Wry>,
		missions::commands::mission_reported,
		missions::commands::mission_answered::<tauri::Wry>,
		notifications::commands::notification_show::<tauri::Wry>,
		plugins::commands::plugin_skills::<tauri::Wry>,
		plugins::commands::plugin_create_skill::<tauri::Wry>,
		plugins::commands::plugin_update_skill::<tauri::Wry>,
		plugins::commands::plugin_set_skill_preloaded::<tauri::Wry>,
		plugins::commands::plugin_delete_skill::<tauri::Wry>,
		plugins::commands::plugin_skill_file::<tauri::Wry>,
		plugins::commands::plugin_write_skill_file::<tauri::Wry>,
		plugins::commands::plugin_delete_skill_file::<tauri::Wry>,
		plugins::commands::plugin_mcp_servers::<tauri::Wry>,
		plugins::commands::plugin_set_mcp_server::<tauri::Wry>,
		plugins::commands::plugin_delete_mcp_server::<tauri::Wry>,
		plugins::commands::plugin_history::<tauri::Wry>,
		plugins::commands::plugin_history_diff::<tauri::Wry>,
		plugins::commands::plugin_revert::<tauri::Wry>,
		routines::commands::routine_trigger_sources::<tauri::Wry>,
		routines::commands::routine_create::<tauri::Wry>,
		routines::commands::routine_update::<tauri::Wry>,
		routines::commands::routine_delete::<tauri::Wry>,
		routines::commands::routine_list,
		routines::commands::routine_runs,
		routines::commands::routine_reported_runs,
		routines::commands::routine_run_now::<tauri::Wry>,
		routines::commands::routine_renew_lease,
		routines::commands::routine_close_run,
		routines::commands::routine_key::<tauri::Wry>,
		search::commands::search_catalogue,
		search::commands::search_messages,
		search::commands::search_recent,
		sections::commands::section_list,
		sections::commands::section_create,
		sections::commands::section_rename,
		sections::commands::roster_pin,
		sections::commands::section_delete,
		sections::commands::bot_move_to_section,
		spaces::commands::space_list,
		spaces::commands::space_create::<tauri::Wry>,
		spaces::commands::space_update,
		spaces::commands::space_reorder,
		spaces::commands::space_delete::<tauri::Wry>,
		spaces::commands::bot_move_to_space,
		spaces::commands::bot_add_to_space,
		spaces::commands::bot_remove_from_space,
		spaces::commands::space_preferences,
		spaces::commands::space_set_preferences,
		user::commands::user_preferences::<tauri::Wry>,
		user::commands::user_set_preferences::<tauri::Wry>,
		user::commands::user_set_profile_picture::<tauri::Wry>,
	]
}
